name: Test on PostgreSQL

on: [ push ]

env:
    DB_DATABASE: adminyard_test
    DB_USER: postgres
    DB_PASSWORD: 12345
    APP_DB_TYPE: pgsql

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                operating_system: ['ubuntu-22.04']
                postgresql-version: [10, 11, 12, 13, 14, 15]
                php_versions:
                    - '8.2'
                include:
                    - operating_system: 'ubuntu-22.04'
                      php_versions: '8.3'
                      postgresql-version: 16

        runs-on: '${{ matrix.operating_system }}'

        steps:
            - uses: actions/checkout@v4

            - name: Install PostgreSQL
              env:
                  POSTGRESQL_VERSION: ${{ matrix.postgresql-version }}
              run: |
                  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
                  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
                  sudo apt-get update
                  sudo apt-get -y install "postgresql-$POSTGRESQL_VERSION"
                  sudo service postgresql start

            - name: Set up PostgreSQL
              run: |
                  sudo -u postgres psql -c "ALTER USER ${{ env.DB_USER }} WITH PASSWORD '${{ env.DB_PASSWORD }}';"
                  sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_DATABASE }} OWNER postgres;"

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_versions }}

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run test cases
              run: php vendor/bin/codecept run
