name: Test on SQLite

on: [ push ]

env:
    APP_DB_TYPE: sqlite

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                operating_system: ['ubuntu-22.04']
                php_versions:
                    - '8.2'
                    - '8.3'

        runs-on: '${{ matrix.operating_system }}'

        steps:
            - uses: actions/checkout@v4

            - name: 'Setup PHP'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_versions }}

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run test cases
              run: php vendor/bin/codecept run
